name: Deploy Datasette with all plugins

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '12 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        path: latest-datasette-with-all-plugins
    - name: Check out datasette
      uses: actions/checkout@v2
      with:
        repository: simonw/datasette
        path: datasette
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/deploy.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pwd
        cd datasette && pip install -e '.[test]'
        pwd
    - name: Build fixtures.db
      run: |
        python datasette/tests/fixtures.py fixtures.db
        pwd
        ls -lah
    - name: Install all plugins
      run: |
        cd latest-datasette-with-all-plugins
        pip install -r plugins.txt
        cd ..
    - name: Test that plugins successfully installed
      run: |
        cd latest-datasette-with-all-plugins
        cat plugins.txt | grep -v '#' | sort > plugins-sorted.txt
        datasette --get /-/plugins.json | jq '.[].name' -r | sort | diff plugins-sorted.txt -
    - name: Set up Cloud Run
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        pwd
        ls -lah
        find /home/runner/work/latest-datasette-with-all-plugins
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun fixtures.db \
            -m metadata.yml \
            --branch=master \
            --extra-options="--config template_debug:1" \
            --service=datasette-with-all-plugins \
            --install=datasette-vega
